# Generated by Django 3.2.9 on 2021-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota4', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
